// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sessionmock

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/session"
)

// NewSessionServiceInterfaceMock creates a new instance of SessionServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionServiceInterfaceMock {
	mock := &SessionServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionServiceInterfaceMock is an autogenerated mock type for the SessionServiceInterface type
type SessionServiceInterfaceMock struct {
	mock.Mock
}

type SessionServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionServiceInterfaceMock) EXPECT() *SessionServiceInterfaceMock_Expecter {
	return &SessionServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateSessionFromFlow provides a mock function for the type SessionServiceInterfaceMock
func (_mock *SessionServiceInterfaceMock) CreateSessionFromFlow(ctx context.Context, in session.CreateSessionInput) (*session.SessionRecord, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateSessionFromFlow")
	}

	var r0 *session.SessionRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.CreateSessionInput) (*session.SessionRecord, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.CreateSessionInput) *session.SessionRecord); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.SessionRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, session.CreateSessionInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionServiceInterfaceMock_CreateSessionFromFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSessionFromFlow'
type SessionServiceInterfaceMock_CreateSessionFromFlow_Call struct {
	*mock.Call
}

// CreateSessionFromFlow is a helper method to define mock.On call
//   - ctx context.Context
//   - in session.CreateSessionInput
func (_e *SessionServiceInterfaceMock_Expecter) CreateSessionFromFlow(ctx interface{}, in interface{}) *SessionServiceInterfaceMock_CreateSessionFromFlow_Call {
	return &SessionServiceInterfaceMock_CreateSessionFromFlow_Call{Call: _e.mock.On("CreateSessionFromFlow", ctx, in)}
}

func (_c *SessionServiceInterfaceMock_CreateSessionFromFlow_Call) Run(run func(ctx context.Context, in session.CreateSessionInput)) *SessionServiceInterfaceMock_CreateSessionFromFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 session.CreateSessionInput
		if args[1] != nil {
			arg1 = args[1].(session.CreateSessionInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionServiceInterfaceMock_CreateSessionFromFlow_Call) Return(sessionRecord *session.SessionRecord, err error) *SessionServiceInterfaceMock_CreateSessionFromFlow_Call {
	_c.Call.Return(sessionRecord, err)
	return _c
}

func (_c *SessionServiceInterfaceMock_CreateSessionFromFlow_Call) RunAndReturn(run func(ctx context.Context, in session.CreateSessionInput) (*session.SessionRecord, error)) *SessionServiceInterfaceMock_CreateSessionFromFlow_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureClientSession provides a mock function for the type SessionServiceInterfaceMock
func (_mock *SessionServiceInterfaceMock) EnsureClientSession(ctx context.Context, sessionID string, clientID string, grantedScopes []string) (*session.ClientSession, error) {
	ret := _mock.Called(ctx, sessionID, clientID, grantedScopes)

	if len(ret) == 0 {
		panic("no return value specified for EnsureClientSession")
	}

	var r0 *session.ClientSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) (*session.ClientSession, error)); ok {
		return returnFunc(ctx, sessionID, clientID, grantedScopes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) *session.ClientSession); ok {
		r0 = returnFunc(ctx, sessionID, clientID, grantedScopes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.ClientSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []string) error); ok {
		r1 = returnFunc(ctx, sessionID, clientID, grantedScopes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionServiceInterfaceMock_EnsureClientSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureClientSession'
type SessionServiceInterfaceMock_EnsureClientSession_Call struct {
	*mock.Call
}

// EnsureClientSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - clientID string
//   - grantedScopes []string
func (_e *SessionServiceInterfaceMock_Expecter) EnsureClientSession(ctx interface{}, sessionID interface{}, clientID interface{}, grantedScopes interface{}) *SessionServiceInterfaceMock_EnsureClientSession_Call {
	return &SessionServiceInterfaceMock_EnsureClientSession_Call{Call: _e.mock.On("EnsureClientSession", ctx, sessionID, clientID, grantedScopes)}
}

func (_c *SessionServiceInterfaceMock_EnsureClientSession_Call) Run(run func(ctx context.Context, sessionID string, clientID string, grantedScopes []string)) *SessionServiceInterfaceMock_EnsureClientSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SessionServiceInterfaceMock_EnsureClientSession_Call) Return(clientSession *session.ClientSession, err error) *SessionServiceInterfaceMock_EnsureClientSession_Call {
	_c.Call.Return(clientSession, err)
	return _c
}

func (_c *SessionServiceInterfaceMock_EnsureClientSession_Call) RunAndReturn(run func(ctx context.Context, sessionID string, clientID string, grantedScopes []string) (*session.ClientSession, error)) *SessionServiceInterfaceMock_EnsureClientSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetClientSessionByID provides a mock function for the type SessionServiceInterfaceMock
func (_mock *SessionServiceInterfaceMock) GetClientSessionByID(ctx context.Context, clientSessionID string) (*session.ClientSession, error) {
	ret := _mock.Called(ctx, clientSessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetClientSessionByID")
	}

	var r0 *session.ClientSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*session.ClientSession, error)); ok {
		return returnFunc(ctx, clientSessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *session.ClientSession); ok {
		r0 = returnFunc(ctx, clientSessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.ClientSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, clientSessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionServiceInterfaceMock_GetClientSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientSessionByID'
type SessionServiceInterfaceMock_GetClientSessionByID_Call struct {
	*mock.Call
}

// GetClientSessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - clientSessionID string
func (_e *SessionServiceInterfaceMock_Expecter) GetClientSessionByID(ctx interface{}, clientSessionID interface{}) *SessionServiceInterfaceMock_GetClientSessionByID_Call {
	return &SessionServiceInterfaceMock_GetClientSessionByID_Call{Call: _e.mock.On("GetClientSessionByID", ctx, clientSessionID)}
}

func (_c *SessionServiceInterfaceMock_GetClientSessionByID_Call) Run(run func(ctx context.Context, clientSessionID string)) *SessionServiceInterfaceMock_GetClientSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionServiceInterfaceMock_GetClientSessionByID_Call) Return(clientSession *session.ClientSession, err error) *SessionServiceInterfaceMock_GetClientSessionByID_Call {
	_c.Call.Return(clientSession, err)
	return _c
}

func (_c *SessionServiceInterfaceMock_GetClientSessionByID_Call) RunAndReturn(run func(ctx context.Context, clientSessionID string) (*session.ClientSession, error)) *SessionServiceInterfaceMock_GetClientSessionByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByID provides a mock function for the type SessionServiceInterfaceMock
func (_mock *SessionServiceInterfaceMock) GetSessionByID(ctx context.Context, sessionID string) (*session.SessionRecord, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByID")
	}

	var r0 *session.SessionRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*session.SessionRecord, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *session.SessionRecord); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.SessionRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionServiceInterfaceMock_GetSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByID'
type SessionServiceInterfaceMock_GetSessionByID_Call struct {
	*mock.Call
}

// GetSessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *SessionServiceInterfaceMock_Expecter) GetSessionByID(ctx interface{}, sessionID interface{}) *SessionServiceInterfaceMock_GetSessionByID_Call {
	return &SessionServiceInterfaceMock_GetSessionByID_Call{Call: _e.mock.On("GetSessionByID", ctx, sessionID)}
}

func (_c *SessionServiceInterfaceMock_GetSessionByID_Call) Run(run func(ctx context.Context, sessionID string)) *SessionServiceInterfaceMock_GetSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionServiceInterfaceMock_GetSessionByID_Call) Return(sessionRecord *session.SessionRecord, err error) *SessionServiceInterfaceMock_GetSessionByID_Call {
	_c.Call.Return(sessionRecord, err)
	return _c
}

func (_c *SessionServiceInterfaceMock_GetSessionByID_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (*session.SessionRecord, error)) *SessionServiceInterfaceMock_GetSessionByID_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveSession provides a mock function for the type SessionServiceInterfaceMock
func (_mock *SessionServiceInterfaceMock) ResolveSession(ctx context.Context, r *http.Request, groupID string) (*session.SessionRecord, error) {
	ret := _mock.Called(ctx, r, groupID)

	if len(ret) == 0 {
		panic("no return value specified for ResolveSession")
	}

	var r0 *session.SessionRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *http.Request, string) (*session.SessionRecord, error)); ok {
		return returnFunc(ctx, r, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *http.Request, string) *session.SessionRecord); ok {
		r0 = returnFunc(ctx, r, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.SessionRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *http.Request, string) error); ok {
		r1 = returnFunc(ctx, r, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionServiceInterfaceMock_ResolveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveSession'
type SessionServiceInterfaceMock_ResolveSession_Call struct {
	*mock.Call
}

// ResolveSession is a helper method to define mock.On call
//   - ctx context.Context
//   - r *http.Request
//   - groupID string
func (_e *SessionServiceInterfaceMock_Expecter) ResolveSession(ctx interface{}, r interface{}, groupID interface{}) *SessionServiceInterfaceMock_ResolveSession_Call {
	return &SessionServiceInterfaceMock_ResolveSession_Call{Call: _e.mock.On("ResolveSession", ctx, r, groupID)}
}

func (_c *SessionServiceInterfaceMock_ResolveSession_Call) Run(run func(ctx context.Context, r *http.Request, groupID string)) *SessionServiceInterfaceMock_ResolveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SessionServiceInterfaceMock_ResolveSession_Call) Return(sessionRecord *session.SessionRecord, err error) *SessionServiceInterfaceMock_ResolveSession_Call {
	_c.Call.Return(sessionRecord, err)
	return _c
}

func (_c *SessionServiceInterfaceMock_ResolveSession_Call) RunAndReturn(run func(ctx context.Context, r *http.Request, groupID string) (*session.SessionRecord, error)) *SessionServiceInterfaceMock_ResolveSession_Call {
	_c.Call.Return(run)
	return _c
}
