// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package session

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewClientSessionStoreInterfaceMock creates a new instance of ClientSessionStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientSessionStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientSessionStoreInterfaceMock {
	mock := &ClientSessionStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClientSessionStoreInterfaceMock is an autogenerated mock type for the ClientSessionStoreInterface type
type ClientSessionStoreInterfaceMock struct {
	mock.Mock
}

type ClientSessionStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientSessionStoreInterfaceMock) EXPECT() *ClientSessionStoreInterfaceMock_Expecter {
	return &ClientSessionStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateClientSession provides a mock function for the type ClientSessionStoreInterfaceMock
func (_mock *ClientSessionStoreInterfaceMock) CreateClientSession(ctx context.Context, cs ClientSession) error {
	ret := _mock.Called(ctx, cs)

	if len(ret) == 0 {
		panic("no return value specified for CreateClientSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClientSession) error); ok {
		r0 = returnFunc(ctx, cs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClientSessionStoreInterfaceMock_CreateClientSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClientSession'
type ClientSessionStoreInterfaceMock_CreateClientSession_Call struct {
	*mock.Call
}

// CreateClientSession is a helper method to define mock.On call
//   - ctx context.Context
//   - cs ClientSession
func (_e *ClientSessionStoreInterfaceMock_Expecter) CreateClientSession(ctx interface{}, cs interface{}) *ClientSessionStoreInterfaceMock_CreateClientSession_Call {
	return &ClientSessionStoreInterfaceMock_CreateClientSession_Call{Call: _e.mock.On("CreateClientSession", ctx, cs)}
}

func (_c *ClientSessionStoreInterfaceMock_CreateClientSession_Call) Run(run func(ctx context.Context, cs ClientSession)) *ClientSessionStoreInterfaceMock_CreateClientSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClientSession
		if args[1] != nil {
			arg1 = args[1].(ClientSession)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientSessionStoreInterfaceMock_CreateClientSession_Call) Return(err error) *ClientSessionStoreInterfaceMock_CreateClientSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClientSessionStoreInterfaceMock_CreateClientSession_Call) RunAndReturn(run func(ctx context.Context, cs ClientSession) error) *ClientSessionStoreInterfaceMock_CreateClientSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetClientSessionByID provides a mock function for the type ClientSessionStoreInterfaceMock
func (_mock *ClientSessionStoreInterfaceMock) GetClientSessionByID(ctx context.Context, clientSessionID string) (*ClientSession, error) {
	ret := _mock.Called(ctx, clientSessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetClientSessionByID")
	}

	var r0 *ClientSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ClientSession, error)); ok {
		return returnFunc(ctx, clientSessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ClientSession); ok {
		r0 = returnFunc(ctx, clientSessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ClientSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, clientSessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientSessionStoreInterfaceMock_GetClientSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientSessionByID'
type ClientSessionStoreInterfaceMock_GetClientSessionByID_Call struct {
	*mock.Call
}

// GetClientSessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - clientSessionID string
func (_e *ClientSessionStoreInterfaceMock_Expecter) GetClientSessionByID(ctx interface{}, clientSessionID interface{}) *ClientSessionStoreInterfaceMock_GetClientSessionByID_Call {
	return &ClientSessionStoreInterfaceMock_GetClientSessionByID_Call{Call: _e.mock.On("GetClientSessionByID", ctx, clientSessionID)}
}

func (_c *ClientSessionStoreInterfaceMock_GetClientSessionByID_Call) Run(run func(ctx context.Context, clientSessionID string)) *ClientSessionStoreInterfaceMock_GetClientSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientSessionStoreInterfaceMock_GetClientSessionByID_Call) Return(clientSession *ClientSession, err error) *ClientSessionStoreInterfaceMock_GetClientSessionByID_Call {
	_c.Call.Return(clientSession, err)
	return _c
}

func (_c *ClientSessionStoreInterfaceMock_GetClientSessionByID_Call) RunAndReturn(run func(ctx context.Context, clientSessionID string) (*ClientSession, error)) *ClientSessionStoreInterfaceMock_GetClientSessionByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetClientSessionBySessionAndClient provides a mock function for the type ClientSessionStoreInterfaceMock
func (_mock *ClientSessionStoreInterfaceMock) GetClientSessionBySessionAndClient(ctx context.Context, sessionID string, clientID string) (*ClientSession, error) {
	ret := _mock.Called(ctx, sessionID, clientID)

	if len(ret) == 0 {
		panic("no return value specified for GetClientSessionBySessionAndClient")
	}

	var r0 *ClientSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*ClientSession, error)); ok {
		return returnFunc(ctx, sessionID, clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *ClientSession); ok {
		r0 = returnFunc(ctx, sessionID, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ClientSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, sessionID, clientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientSessionStoreInterfaceMock_GetClientSessionBySessionAndClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientSessionBySessionAndClient'
type ClientSessionStoreInterfaceMock_GetClientSessionBySessionAndClient_Call struct {
	*mock.Call
}

// GetClientSessionBySessionAndClient is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - clientID string
func (_e *ClientSessionStoreInterfaceMock_Expecter) GetClientSessionBySessionAndClient(ctx interface{}, sessionID interface{}, clientID interface{}) *ClientSessionStoreInterfaceMock_GetClientSessionBySessionAndClient_Call {
	return &ClientSessionStoreInterfaceMock_GetClientSessionBySessionAndClient_Call{Call: _e.mock.On("GetClientSessionBySessionAndClient", ctx, sessionID, clientID)}
}

func (_c *ClientSessionStoreInterfaceMock_GetClientSessionBySessionAndClient_Call) Run(run func(ctx context.Context, sessionID string, clientID string)) *ClientSessionStoreInterfaceMock_GetClientSessionBySessionAndClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ClientSessionStoreInterfaceMock_GetClientSessionBySessionAndClient_Call) Return(clientSession *ClientSession, err error) *ClientSessionStoreInterfaceMock_GetClientSessionBySessionAndClient_Call {
	_c.Call.Return(clientSession, err)
	return _c
}

func (_c *ClientSessionStoreInterfaceMock_GetClientSessionBySessionAndClient_Call) RunAndReturn(run func(ctx context.Context, sessionID string, clientID string) (*ClientSession, error)) *ClientSessionStoreInterfaceMock_GetClientSessionBySessionAndClient_Call {
	_c.Call.Return(run)
	return _c
}

// TouchClientSession provides a mock function for the type ClientSessionStoreInterfaceMock
func (_mock *ClientSessionStoreInterfaceMock) TouchClientSession(ctx context.Context, clientSessionID string, lastUsedAt time.Time) error {
	ret := _mock.Called(ctx, clientSessionID, lastUsedAt)

	if len(ret) == 0 {
		panic("no return value specified for TouchClientSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, clientSessionID, lastUsedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClientSessionStoreInterfaceMock_TouchClientSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TouchClientSession'
type ClientSessionStoreInterfaceMock_TouchClientSession_Call struct {
	*mock.Call
}

// TouchClientSession is a helper method to define mock.On call
//   - ctx context.Context
//   - clientSessionID string
//   - lastUsedAt time.Time
func (_e *ClientSessionStoreInterfaceMock_Expecter) TouchClientSession(ctx interface{}, clientSessionID interface{}, lastUsedAt interface{}) *ClientSessionStoreInterfaceMock_TouchClientSession_Call {
	return &ClientSessionStoreInterfaceMock_TouchClientSession_Call{Call: _e.mock.On("TouchClientSession", ctx, clientSessionID, lastUsedAt)}
}

func (_c *ClientSessionStoreInterfaceMock_TouchClientSession_Call) Run(run func(ctx context.Context, clientSessionID string, lastUsedAt time.Time)) *ClientSessionStoreInterfaceMock_TouchClientSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ClientSessionStoreInterfaceMock_TouchClientSession_Call) Return(err error) *ClientSessionStoreInterfaceMock_TouchClientSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClientSessionStoreInterfaceMock_TouchClientSession_Call) RunAndReturn(run func(ctx context.Context, clientSessionID string, lastUsedAt time.Time) error) *ClientSessionStoreInterfaceMock_TouchClientSession_Call {
	_c.Call.Return(run)
	return _c
}
