// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package session

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewSessionRecordStoreInterfaceMock creates a new instance of SessionRecordStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRecordStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRecordStoreInterfaceMock {
	mock := &SessionRecordStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionRecordStoreInterfaceMock is an autogenerated mock type for the SessionRecordStoreInterface type
type SessionRecordStoreInterfaceMock struct {
	mock.Mock
}

type SessionRecordStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRecordStoreInterfaceMock) EXPECT() *SessionRecordStoreInterfaceMock_Expecter {
	return &SessionRecordStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type SessionRecordStoreInterfaceMock
func (_mock *SessionRecordStoreInterfaceMock) CreateSession(ctx context.Context, rec SessionRecord) error {
	ret := _mock.Called(ctx, rec)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, SessionRecord) error); ok {
		r0 = returnFunc(ctx, rec)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRecordStoreInterfaceMock_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type SessionRecordStoreInterfaceMock_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - rec SessionRecord
func (_e *SessionRecordStoreInterfaceMock_Expecter) CreateSession(ctx interface{}, rec interface{}) *SessionRecordStoreInterfaceMock_CreateSession_Call {
	return &SessionRecordStoreInterfaceMock_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, rec)}
}

func (_c *SessionRecordStoreInterfaceMock_CreateSession_Call) Run(run func(ctx context.Context, rec SessionRecord)) *SessionRecordStoreInterfaceMock_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 SessionRecord
		if args[1] != nil {
			arg1 = args[1].(SessionRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRecordStoreInterfaceMock_CreateSession_Call) Return(err error) *SessionRecordStoreInterfaceMock_CreateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRecordStoreInterfaceMock_CreateSession_Call) RunAndReturn(run func(ctx context.Context, rec SessionRecord) error) *SessionRecordStoreInterfaceMock_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByHandle provides a mock function for the type SessionRecordStoreInterfaceMock
func (_mock *SessionRecordStoreInterfaceMock) GetSessionByHandle(ctx context.Context, handleID string) (*SessionRecord, error) {
	ret := _mock.Called(ctx, handleID)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByHandle")
	}

	var r0 *SessionRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*SessionRecord, error)); ok {
		return returnFunc(ctx, handleID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *SessionRecord); ok {
		r0 = returnFunc(ctx, handleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SessionRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, handleID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRecordStoreInterfaceMock_GetSessionByHandle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByHandle'
type SessionRecordStoreInterfaceMock_GetSessionByHandle_Call struct {
	*mock.Call
}

// GetSessionByHandle is a helper method to define mock.On call
//   - ctx context.Context
//   - handleID string
func (_e *SessionRecordStoreInterfaceMock_Expecter) GetSessionByHandle(ctx interface{}, handleID interface{}) *SessionRecordStoreInterfaceMock_GetSessionByHandle_Call {
	return &SessionRecordStoreInterfaceMock_GetSessionByHandle_Call{Call: _e.mock.On("GetSessionByHandle", ctx, handleID)}
}

func (_c *SessionRecordStoreInterfaceMock_GetSessionByHandle_Call) Run(run func(ctx context.Context, handleID string)) *SessionRecordStoreInterfaceMock_GetSessionByHandle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRecordStoreInterfaceMock_GetSessionByHandle_Call) Return(sessionRecord *SessionRecord, err error) *SessionRecordStoreInterfaceMock_GetSessionByHandle_Call {
	_c.Call.Return(sessionRecord, err)
	return _c
}

func (_c *SessionRecordStoreInterfaceMock_GetSessionByHandle_Call) RunAndReturn(run func(ctx context.Context, handleID string) (*SessionRecord, error)) *SessionRecordStoreInterfaceMock_GetSessionByHandle_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByID provides a mock function for the type SessionRecordStoreInterfaceMock
func (_mock *SessionRecordStoreInterfaceMock) GetSessionByID(ctx context.Context, sessionID string) (*SessionRecord, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByID")
	}

	var r0 *SessionRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*SessionRecord, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *SessionRecord); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SessionRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRecordStoreInterfaceMock_GetSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByID'
type SessionRecordStoreInterfaceMock_GetSessionByID_Call struct {
	*mock.Call
}

// GetSessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *SessionRecordStoreInterfaceMock_Expecter) GetSessionByID(ctx interface{}, sessionID interface{}) *SessionRecordStoreInterfaceMock_GetSessionByID_Call {
	return &SessionRecordStoreInterfaceMock_GetSessionByID_Call{Call: _e.mock.On("GetSessionByID", ctx, sessionID)}
}

func (_c *SessionRecordStoreInterfaceMock_GetSessionByID_Call) Run(run func(ctx context.Context, sessionID string)) *SessionRecordStoreInterfaceMock_GetSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRecordStoreInterfaceMock_GetSessionByID_Call) Return(sessionRecord *SessionRecord, err error) *SessionRecordStoreInterfaceMock_GetSessionByID_Call {
	_c.Call.Return(sessionRecord, err)
	return _c
}

func (_c *SessionRecordStoreInterfaceMock_GetSessionByID_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (*SessionRecord, error)) *SessionRecordStoreInterfaceMock_GetSessionByID_Call {
	_c.Call.Return(run)
	return _c
}

// TouchSession provides a mock function for the type SessionRecordStoreInterfaceMock
func (_mock *SessionRecordStoreInterfaceMock) TouchSession(ctx context.Context, sessionID string, lastActiveAt time.Time, version int) (bool, error) {
	ret := _mock.Called(ctx, sessionID, lastActiveAt, version)

	if len(ret) == 0 {
		panic("no return value specified for TouchSession")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, int) (bool, error)); ok {
		return returnFunc(ctx, sessionID, lastActiveAt, version)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, int) bool); ok {
		r0 = returnFunc(ctx, sessionID, lastActiveAt, version)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, int) error); ok {
		r1 = returnFunc(ctx, sessionID, lastActiveAt, version)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRecordStoreInterfaceMock_TouchSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TouchSession'
type SessionRecordStoreInterfaceMock_TouchSession_Call struct {
	*mock.Call
}

// TouchSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - lastActiveAt time.Time
//   - version int
func (_e *SessionRecordStoreInterfaceMock_Expecter) TouchSession(ctx interface{}, sessionID interface{}, lastActiveAt interface{}, version interface{}) *SessionRecordStoreInterfaceMock_TouchSession_Call {
	return &SessionRecordStoreInterfaceMock_TouchSession_Call{Call: _e.mock.On("TouchSession", ctx, sessionID, lastActiveAt, version)}
}

func (_c *SessionRecordStoreInterfaceMock_TouchSession_Call) Run(run func(ctx context.Context, sessionID string, lastActiveAt time.Time, version int)) *SessionRecordStoreInterfaceMock_TouchSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SessionRecordStoreInterfaceMock_TouchSession_Call) Return(b bool, err error) *SessionRecordStoreInterfaceMock_TouchSession_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *SessionRecordStoreInterfaceMock_TouchSession_Call) RunAndReturn(run func(ctx context.Context, sessionID string, lastActiveAt time.Time, version int) (bool, error)) *SessionRecordStoreInterfaceMock_TouchSession_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSessionAuth provides a mock function for the type SessionRecordStoreInterfaceMock
func (_mock *SessionRecordStoreInterfaceMock) UpdateSessionAuth(ctx context.Context, sessionID string, factors []AuthFactor, assuranceLevel string, authenticatedAt time.Time) error {
	ret := _mock.Called(ctx, sessionID, factors, assuranceLevel, authenticatedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSessionAuth")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []AuthFactor, string, time.Time) error); ok {
		r0 = returnFunc(ctx, sessionID, factors, assuranceLevel, authenticatedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRecordStoreInterfaceMock_UpdateSessionAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSessionAuth'
type SessionRecordStoreInterfaceMock_UpdateSessionAuth_Call struct {
	*mock.Call
}

// UpdateSessionAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - factors []AuthFactor
//   - assuranceLevel string
//   - authenticatedAt time.Time
func (_e *SessionRecordStoreInterfaceMock_Expecter) UpdateSessionAuth(ctx interface{}, sessionID interface{}, factors interface{}, assuranceLevel interface{}, authenticatedAt interface{}) *SessionRecordStoreInterfaceMock_UpdateSessionAuth_Call {
	return &SessionRecordStoreInterfaceMock_UpdateSessionAuth_Call{Call: _e.mock.On("UpdateSessionAuth", ctx, sessionID, factors, assuranceLevel, authenticatedAt)}
}

func (_c *SessionRecordStoreInterfaceMock_UpdateSessionAuth_Call) Run(run func(ctx context.Context, sessionID string, factors []AuthFactor, assuranceLevel string, authenticatedAt time.Time)) *SessionRecordStoreInterfaceMock_UpdateSessionAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []AuthFactor
		if args[2] != nil {
			arg2 = args[2].([]AuthFactor)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *SessionRecordStoreInterfaceMock_UpdateSessionAuth_Call) Return(err error) *SessionRecordStoreInterfaceMock_UpdateSessionAuth_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRecordStoreInterfaceMock_UpdateSessionAuth_Call) RunAndReturn(run func(ctx context.Context, sessionID string, factors []AuthFactor, assuranceLevel string, authenticatedAt time.Time) error) *SessionRecordStoreInterfaceMock_UpdateSessionAuth_Call {
	_c.Call.Return(run)
	return _c
}
